version: 2.1

orbs:
  slack: m-88888888/slack-notify-orb@dev:first

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: echo "hello world"
      - run: echo hoge
      - slack/notify:
          event: fail

