version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:17.2.0 # ジョブのコマンドが実行されるプライマリ コンテナ
    steps:
      - checkout # プロジェクト ディレクトリ内のコードをチェックアウトします
      - run: echo "hello world" # `echo` コマンドを実行します
