version: 2.1

orbs:
  slack: m-88888888/slack-notify-orb@dev:first

jobs:
  build:
    working_directory: ~/$(CIRCLE_PROJECT_REPONAME)
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world"
      - run: echo $(git log -1 HEAD --pretty=format:%s)
      - run: echo "export COMMIT_MESSAGE=\"$(git log --format=%B -n 1 $CIRCLE_SHA1)\""
      - run: xxx
      - slack/notify:
          event: fail
