version: 2.1

orbs:
  slack: m-88888888/slack-notify-orb@1.0.0

jobs:
  build:
    working_directory: ~/$(CIRCLE_PROJECT_REPONAME)
    docker:
      - image: cimg/node:17.2.0
    steps:
      - run: exit 0
      - slack/notify:
          slack_name_mappings: '{ "<@U028A93RR5F>": "m-88888888", "<@Uhogehoge>": "TestUser" }'
          deploy_flag: false
